### ISSUE TITLE
Rely on template formula instead of contrasts

### ISSUE THREAD

**Issue by kleinschmidt** [beacon-biosignals/Effects.jl#16]
Relying on the contrasts can be potentially dangerous since the ordering of the levels and the levels themselves (and center for a CenteredTerm from StandardizedPredictors.jl) are determined from the data if not specified in the contrasts, so it's possible that you'd get different contrast coding if someone specified, e.g., `contrasts=Dict(:x => EffectsCoding(), :y => Center())` and passed in a reference grid.

A better alternative is to match the Terms that are present in the 'effects formula' with a 'model formula' that was actually used to generate the modelcols for the model fit.  Something like finding a matching terms based on [`StatsModels.symequal`/`termsyms`](https://github.com/JuliaStats/StatsModels.jl/blob/0d0c2bbd56b183491e8c831a92168d4265e4ea68/src/schema.jl#L377-L384).

**Comment by palday** [comment]
Closed by #19
