### ISSUE TITLE
Effect plot does not display the Y-axis name

### ISSUE THREAD

**Issue by Reulguen** [beacon-biosignals/Effects.jl#86]
Hi,

I created a plot as in this example: 
```julia
plt = data(refgrid) * mapping(:age, :weight; color=:sex) *
      (visual(Lines) + mapping(; lower=:lower, upper=:upper) * visual(LinesFill))
draw(plt)
```

Mine looks as following:

```julia
plt1 =  data(eff_interac) * mapping(:number => "number", :uV => "fitted mean amplitude";  color = :condition, col=:ROI) * 
  (visual(Lines) + visual(Scatter) + mapping(;lower=:lower, upper=:upper) * visual(LinesFill))
draw(plt1)
```

When I add `+ mapping(; lower=:lower, upper=:upper) * visual(LinesFill)`, the Y-axis name "fitted mean amplitude" is not displayed in the plot. Do you have a solution?

Thank you!

**Comment by palday** [comment]
This is more of an issue with AlgebraOfGraphics than Effects...but I believe you could specify the axis to draw into or pass appropriate keyword arguments, e.g.

```julia
draw(plt1; axis=(;ylabel="fitted mean amplitude")
```

**Comment by Reulguen** [comment]
Great! This solved it, thank you.
